### ISSUE TITLE
Rewarder APRs show when rewarder is empty

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beethovenx-backend#108]
![Image](https://user-images.githubusercontent.com/93920061/186917456-63531a88-fbab-4e78-b5f5-4f627f8ac483.png)

**Comment by franzns** [comment]
they don't have any rewarder rewards but still show the apr

**Comment by 0xSkly** [comment]
resolved by 296660c1ac0bfd6bb070939e1b7d92cc3ca9a051
