### ISSUE TITLE
Test graph-node/rpc setup

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beethovenx-backend#30]
Different setups possible, either host ourselves or on thegraph. Or something in between.

Starting to analyze drifts: https://datastudio.google.com/u/0/reporting/96d36ce2-1f94-4b90-a5b3-37e8f79038ba/page/PNmsC/edit

**Comment by franzns** [comment]
A graph node costs ~2.6k/month (without the RPC cost)

**Comment by franzns** [comment]
analysis can be found here: https://docs.google.com/document/d/1MFem6mK7iE4kyCLR_o9kDOXwb6bxZFgM2AsjEvE96gE/edit

**Comment by franzns** [comment]
For an RPC node, we need a m5a.2xlarge machine and 2.5TB storage (which is also increasing...). This costs more than a hosted enterprise one from Ankr:
<html>
<body>
<google-sheets-html-origin>

what | cost / instance | cost total
-- | -- | --
graph tiny node | 93.77 | 187.54
m5a.large | 75.92 |  
150gb storage | 17.85 |  
  |   |  
graph incl rpc | 541.68 | 1083.36
m5a.2xlarge | 303.68 |  
2500gb storage | 238 |  
  |   |  
Diff |   | 895.82
  |   |  
Ankr enterprise node |   | 850


</body>
</html>


my recommendation would be to run our own tinynode for the changelog subgraph and pay ankr for an enterprise node. This node can also be used to actually run the queries against.

**Comment by franzns** [comment]
Ankr offered that we can test their services before buying.

**Comment by 0xSkly** [comment]
We settled public RPC nodes with the graph hosted service, lets discuss this further in regards of the graph moving to decentralized network
