### ISSUE TITLE
Wrong APR data

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beethovenx-backend#41]
APR in overview & details page do not match. Related to this issue https://github.com/beethovenxfi/beets-frontend/issues/66

**Comment by danielmkm** [comment]
https://github.com/beethovenxfi/beethovenx-backend/commit/b189d24734c9a82bc811e8be17b8cb83f20432fc

**Comment by 0xSkly** [comment]
resolved by https://github.com/beethovenxfi/beethovenx-backend/commit/b189d24734c9a82bc811e8be17b8cb83f20432fc
