### ISSUE TITLE
incorrect display of graphs

### ISSUE THREAD

**Issue by 0xsouvlaki** [beethovenxfi/beethovenx-backend#46]
For all Optimism pools the TVL/ Volume graph is showing inconsistent data which makes it look like volume dropped off. 

![image](https://user-images.githubusercontent.com/102611720/182678388-8171a6dd-7e53-4c2e-a300-e33000386a98.png)

As you can see the volume for Jul 30 shows 842k. as per the subgraph this was the total at that date

![image](https://user-images.githubusercontent.com/102611720/182678608-63a41f93-b065-4347-ab04-5eee1ae4c47e.png)

From the next day, the graph changes to display the difference between the two snapshot points (correct 24h volume)

**Comment by 0xSkly** [comment]
it was using the wrong numbers until the drop, but the older entries were not rerun, i've done this now so the issue should be fixed
