### ISSUE TITLE
APRs showing values from multiple gauges

### ISSUE THREAD

**Issue by gmbronco** [beethovenxfi/beethovenx-backend#462]
Querying the APR items returns a list that includes APRs from both current and outdated gauges. This can lead to incorrect values being displayed in the frontend.

To address this issue and assuming we want to keep APRs from outdated sources, there are two potential solutions:

1. Include Gauge Status in aprItem Title:
We can store the gauge status in the title of each aprItem. This would enable us to filter out non-preferential gauges more effectively.

2. Associate aprItem with a Gauge:
Alternatively, we can associate each aprItem with a specific gauge. This association would allow us to include gauge-specific data in the response, making it easier to distinguish between APRs from different gauges and maintain accuracy in the frontend.

Example query with the mixed up APRs:
```
{
  poolGetPools(
    where: {
      idIn:[
        "0x32df62dc3aed2cd6224193052ce665dc181658410002000000000000000003bd",
      ],
    }
  ) {
    id
    name
    chain
    dynamicData {
      apr {
        items {
          title
          apr {
            ... on GqlPoolAprTotal {
              total
            }
            ... on GqlPoolAprRange {
              min
            }
          }
        }
      }
    }
  }
}
```

**Comment by franzns** [comment]
The origin of this issue is that outdated gauges still have APRs, why is that so? We need to find that out first, before taking any remediating action.
