### ISSUE TITLE
Allow multichain queries for user service

### ISSUE THREAD

**Issue by gmbronco** [beethovenxfi/beethovenx-backend#481]
Change the queries to allow filtering based on chainIDs, instead of relying solely on the default chainID passed in a header. Filter should include the header chainId to maintain backward compatibility.

From Daniel:
You'd need to update the user queries to support an array of chains:
```
extend type Query {
    userGetPoolBalances(chains: [GqlChain!]!): [GqlUserPoolBalance!]!
    userGetStaking(chains: [GqlChain!]!): [GqlPoolStaking!]!
```

**Comment by franzns** [comment]
Done for PoolBalances, pending for staking

**Comment by franzns** [comment]
also change the user ID to be passed via param in addition to header

**Comment by franzns** [comment]
https://github.com/beethovenxfi/beethovenx-backend/pull/518
