### ISSUE TITLE
fix veBAL users ranking

### ISSUE THREAD

**Issue by mendesfabio** [beethovenxfi/beethovenx-backend#497]
While I was exploring the API code I noticed the `balance` field from `PrismaVeBalUserBalance` is `String`. That makes ordering not working as expected and breaks the user ranking.

https://github.com/beethovenxfi/beethovenx-backend/blob/e4548c94b7d677ffad648adb6301f59012f9f3f2/modules/vebal/vebal.service.ts#L34

I confirmed the issue querying Humpy's rank which should be 2 according to our [veBAL dashboard](https://dune.com/balancer/vebal-analysis).

<img width="428" alt="image" src="https://github.com/beethovenxfi/beethovenx-backend/assets/43360747/dc914d69-7efc-4ad3-9fa7-bac62170b8cb">

I ended up fixing the issue locally and committed to https://github.com/beethovenxfi/beethovenx-backend/commit/9d898ddd8cf61ca62ac685045e5b570d5a50f0f3 but I'm still wondering what's the best approach for this and what you guys agreed on with regard to number types. Maybe a better solution here would be to add a `balanceNum` column instead of altering the type of `balance` - just found this on `PrismaUserStakedBalance` model while writing this issue 😅

**Comment by franzns** [comment]
ha, good catch! we should store big numbers as strings as much as possible since it can easily exceed precision of numbers. Best would be to fix the query in the vebal.service.ts to sort after one got the response from the DB. You mind implementing that?
