### ISSUE TITLE
`tokens` missing BPT in for ComposableStable pools

### ISSUE THREAD

**Issue by johngrantuk** [beethovenxfi/beethovenx-backend#528]
BPT is missing from tokens for ComposableStables when we use [this query](https://github.com/balancer/b-sdk/blob/097ac9e5fde2fca967c130c45075731d9e4d7d96/src/data/providers/balancer-api/modules/pool-state/index.ts)

**Comment by franzns** [comment]
PR ready, waiting from confirmation of impact into our UI from @groninge01

**Comment by franzns** [comment]
https://github.com/beethovenxfi/beethovenx-backend/pull/536

**Comment by franzns** [comment]
deployed to test, waiting for push to prod https://github.com/beethovenxfi/beethovenx-backend/pull/547
