### ISSUE TITLE
investment still visible after withdraw

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beethovenx-backend#62]
A month ago, the address 0x500F8fe004E978D1c58dba852BfE7bBa8Ae434c1 withdrew everything from pool 0xecaa1cbd28459d34b766f9195413cb20122fb942000200000000000000000120. It is still showing under my investments and it's added to my total amount. On the pool detail page, it's not visible, which is correct.

**Comment by 0xSkly** [comment]
seems like the database was not initialized correctly, can you check again @franzns

**Comment by franzns** [comment]
fixed
