### ISSUE TITLE
my investments show pool with 0$ investment, bpt dust in wallet

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beethovenx-backend#63]
Address 0x500F8fe004E978D1c58dba852BfE7bBa8Ae434c1 shows pool https://v2.beets.fi/pool/0xdfc65c1f15ad3507754ef0fd4ba67060c108db7e000000000000000000000406 in my investment list although 0$ are invested. Have had investments in that pool long time ago.

![Image](https://user-images.githubusercontent.com/93920061/183618265-952aa6ee-df3f-406d-859e-ba0c189d3195.png)

**Comment by 0xSkly** [comment]
might get resolved by #64

**Comment by franzns** [comment]
Oh, I think it's because I have BPT dust in my wallet.

**Comment by 0xSkly** [comment]
ah yea, we should filter them out in the backend

**Comment by 0xSkly** [comment]
closing in favour of https://github.com/beethovenxfi/beets-frontend/issues/123
