### ISSUE TITLE
Expose last synced block for wallet and staked balances in query

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beethovenx-backend#65]
We should expose the latest synced block for wallet & staked balances on a query.

I would propose to expose it on the protocol resolver.

The data can be found in the `PrismaUserBalanceSyncStatus` table.

![Image](https://user-images.githubusercontent.com/91403802/183650959-de49a134-0f2f-446b-9204-1eb31653300b.png)

**Comment by danielmkm** [comment]
Would also be nice to have a mutation to force a balance update for a user address

**Comment by 0xSkly** [comment]
you mean like the `userSyncBalance` mutation just for all pools ?

**Comment by franzns** [comment]
I'd also add the latest synced block for pool sync, needed for defilama.

So I propose to add the following data to the protocolMetrics:
```
    userWalletSyncBlock: Scalars['BigInt'];
    userStakeSyncBlock: Scalars['BigInt'];
    poolSyncBlock: Scalars['BigInt'];
```

**Comment by franzns** [comment]
> Would also be nice to have a mutation to force a balance update for a user address

You'd like an update for all pools for a specific user address? check #71

**Comment by franzns** [comment]
#71 merged
