### ISSUE TITLE
graph data for aug 10 missing in some pools

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beethovenx-backend#74]
some pools miss snapshot data for aug 10.

e.g.
https://v2.beets.fi/pool/0xa10285f445bcb521f1d623300dc4998b02f11c8f00000000000000000000043b
https://v2.beets.fi/pool/0xa55318e5d8b7584b8c0e5d3636545310bf9eeb8f000000000000000000000337

**Comment by 0xSkly** [comment]
Resolved by cf34490125a5a0e0059014f6f215ac6c3b2ab7bb
