### ISSUE TITLE
Volume (24h) and Fees (24h) on boosted pools higher (2.5x) on v2 than on v1

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beethovenx-backend#85]
Boosted pools have higher 24h volume and 24hfee (and therefore swapfee apr) on v2 than on v1. The question is, who is wrong?

See examples:

https://beets.fi/#/pool/0xc0064b291bd3d4ba0e44ccfc81bf8e7f7a579cd200000000000000000000042c 
![Image](https://user-images.githubusercontent.com/93920061/185031394-028ae230-17a5-4bfd-bdd3-a00b205cb051.png)

https://v2.beets.fi/pool/0xc0064b291bd3d4ba0e44ccfc81bf8e7f7a579cd200000000000000000000042c
![Image](https://user-images.githubusercontent.com/93920061/185031442-4741debc-b4ad-4a25-82d1-810c5ff3388d.png)

https://beets.fi/#/pool/0x10441785a928040b456a179691141c48356eb3a50001000000000000000002fa
![Image](https://user-images.githubusercontent.com/93920061/185031480-af8db4bf-f65e-4987-910f-d955f77f078c.png)

https://v2.beets.fi/pool/0x10441785a928040b456a179691141c48356eb3a50001000000000000000002fa
![Image](https://user-images.githubusercontent.com/93920061/185031522-79631ec0-9a57-48ef-a1d5-d84b96d5a146.png)

**Comment by danielmkm** [comment]
can you dig into this discrepencies here, see where they come from.

**Comment by franzns** [comment]
joins/exits are excluded from volume and fee

**Comment by franzns** [comment]
bpt swaps got a price in the subgraph, didn't account for that. now getting price from priceservice if bpt is in a swap.
