### ISSUE TITLE
Calculate beets price from fidelio duetto pool instead of coingecko and expose in dedicated query

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beethovenx-backend#87]
Currently, the beets price is taken from coingecko which sometimes is not accurate. We therefore should go back to calculate it based on our own pools. On V1, it was calculated based on 80/20 beets/usdc pool but we should use the fidelio duetto pool cause of deeper liquidity.

Therefore, we need a new price handler in addition to the fbeets price handler
<img width="778" alt="image" src="https://user-images.githubusercontent.com/91403802/185073381-3a3154e6-9b16-4db7-bde9-85b96492d33a.png">

We also need a deciated query which just exposed the beets price

**Comment by franzns** [comment]
use on-chain data to get pool details, hardcode beetspriceprovider rpc so it works on both op and ftm. 
integrate into price updates.

**Comment by franzns** [comment]
merged #89
